import 'next-logger'
import './globals.css'
import type { Metadata } from 'next'
import { PropsWithChildren, ReactElement } from 'react'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren): ReactElement {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
