apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: dash
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://tsm.intern.nav.no'
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - 'NAVident'
        groups:
          - id: "3a541678-8965-45c4-844b-486a8b9b94a3"
    sidecar:
      enabled: true
      autoLogin: true
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
  readiness:
    path: /api/internal/is_ready
    initialDelay: 10
